version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - unused
    - wastedassign
    - contextcheck
    - revive

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln

    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true

    govet:
      enable:
        - appends
        - assign
        - atomic
        - bools
        - buildtag
        - composites
        - copylocks
        - defers
        - directive
        - errorsas
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - printf
        - shift
        - sigchanyzer
        - slog
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite

    misspell:
      locale: US
      ignore-rules:
        - cancelled

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming

  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - contextcheck
      - text: avoid package names that conflict with Go standard library package names
        linters:
          - revive
      - text: avoid meaningless package names
        linters:
          - revive
      - path: internal/toy.*
        linters:
          - contextcheck
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

formatters:
  enable:
    - gofmt
